//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoInstanceKey : XPObject
    {
        Guid fKeyId;
        public Guid KeyId
        {
            get { return fKeyId; }
            set { SetPropertyValue<Guid>(nameof(KeyId), ref fKeyId, value); }
        }
        Guid fInstanceId;
        public Guid InstanceId
        {
            get { return fInstanceId; }
            set { SetPropertyValue<Guid>(nameof(InstanceId), ref fInstanceId, value); }
        }
        string fProperties;
        [Size(SizeAttribute.Unlimited)]
        public string Properties
        {
            get { return fProperties; }
            set { SetPropertyValue<string>(nameof(Properties), ref fProperties, value); }
        }
    }

}
