//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoRunningWorkflowInstanceInfo : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fWorkflowName;
        [Size(255)]
        public string WorkflowName
        {
            get { return fWorkflowName; }
            set { SetPropertyValue<string>(nameof(WorkflowName), ref fWorkflowName, value); }
        }
        string fWorkflowUniqueId;
        [Size(255)]
        public string WorkflowUniqueId
        {
            get { return fWorkflowUniqueId; }
            set { SetPropertyValue<string>(nameof(WorkflowUniqueId), ref fWorkflowUniqueId, value); }
        }
        string fTargetObjectHandle;
        [Size(255)]
        public string TargetObjectHandle
        {
            get { return fTargetObjectHandle; }
            set { SetPropertyValue<string>(nameof(TargetObjectHandle), ref fTargetObjectHandle, value); }
        }
        Guid fActivityInstanceId;
        public Guid ActivityInstanceId
        {
            get { return fActivityInstanceId; }
            set { SetPropertyValue<Guid>(nameof(ActivityInstanceId), ref fActivityInstanceId, value); }
        }
        string fState;
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
    }

}
