//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoStateMachine : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>(nameof(TargetObjectType), ref fTargetObjectType, value); }
        }
        string fStatePropertyName;
        public string StatePropertyName
        {
            get { return fStatePropertyName; }
            set { SetPropertyValue<string>(nameof(StatePropertyName), ref fStatePropertyName, value); }
        }
        XpoState fStartState;
        [Association(@"XpoStateMachineReferencesXpoState")]
        public XpoState StartState
        {
            get { return fStartState; }
            set { SetPropertyValue<XpoState>(nameof(StartState), ref fStartState, value); }
        }
        bool fExpandActionsInDetailView;
        public bool ExpandActionsInDetailView
        {
            get { return fExpandActionsInDetailView; }
            set { SetPropertyValue<bool>(nameof(ExpandActionsInDetailView), ref fExpandActionsInDetailView, value); }
        }
        [Association(@"XpoStateReferencesXpoStateMachine")]
        public XPCollection<XpoState> XpoStates { get { return GetCollection<XpoState>(nameof(XpoStates)); } }
    }

}
