//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoStateAppearance : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        XpoState fState;
        [Association(@"XpoStateAppearanceReferencesXpoState")]
        public XpoState State
        {
            get { return fState; }
            set { SetPropertyValue<XpoState>(nameof(State), ref fState, value); }
        }
        string fAppearanceItemType;
        public string AppearanceItemType
        {
            get { return fAppearanceItemType; }
            set { SetPropertyValue<string>(nameof(AppearanceItemType), ref fAppearanceItemType, value); }
        }
        string fContext;
        public string Context
        {
            get { return fContext; }
            set { SetPropertyValue<string>(nameof(Context), ref fContext, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>(nameof(Criteria), ref fCriteria, value); }
        }
        string fMethod;
        public string Method
        {
            get { return fMethod; }
            set { SetPropertyValue<string>(nameof(Method), ref fMethod, value); }
        }
        string fTargetItems;
        public string TargetItems
        {
            get { return fTargetItems; }
            set { SetPropertyValue<string>(nameof(TargetItems), ref fTargetItems, value); }
        }
        int fPriority;
        public int Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<int>(nameof(Priority), ref fPriority, value); }
        }
        int fFontColor;
        public int FontColor
        {
            get { return fFontColor; }
            set { SetPropertyValue<int>(nameof(FontColor), ref fFontColor, value); }
        }
        int fBackColor;
        public int BackColor
        {
            get { return fBackColor; }
            set { SetPropertyValue<int>(nameof(BackColor), ref fBackColor, value); }
        }
        int fFontStyle;
        public int FontStyle
        {
            get { return fFontStyle; }
            set { SetPropertyValue<int>(nameof(FontStyle), ref fFontStyle, value); }
        }
        bool fEnabled;
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>(nameof(Enabled), ref fEnabled, value); }
        }
        int fVisibility;
        public int Visibility
        {
            get { return fVisibility; }
            set { SetPropertyValue<int>(nameof(Visibility), ref fVisibility, value); }
        }
    }

}
