//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoState : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCaption;
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>(nameof(Caption), ref fCaption, value); }
        }
        XpoStateMachine fStateMachine;
        [Association(@"XpoStateReferencesXpoStateMachine")]
        public XpoStateMachine StateMachine
        {
            get { return fStateMachine; }
            set { SetPropertyValue<XpoStateMachine>(nameof(StateMachine), ref fStateMachine, value); }
        }
        string fMarkerValue;
        [Size(SizeAttribute.Unlimited)]
        public string MarkerValue
        {
            get { return fMarkerValue; }
            set { SetPropertyValue<string>(nameof(MarkerValue), ref fMarkerValue, value); }
        }
        string fTargetObjectCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string TargetObjectCriteria
        {
            get { return fTargetObjectCriteria; }
            set { SetPropertyValue<string>(nameof(TargetObjectCriteria), ref fTargetObjectCriteria, value); }
        }
        [Association(@"XpoStateAppearanceReferencesXpoState")]
        public XPCollection<XpoStateAppearance> XpoStateAppearances { get { return GetCollection<XpoStateAppearance>(nameof(XpoStateAppearances)); } }
        [Association(@"XpoStateMachineReferencesXpoState")]
        public XPCollection<XpoStateMachine> XpoStateMachines { get { return GetCollection<XpoStateMachine>(nameof(XpoStateMachines)); } }
        [Association(@"XpoTransitionReferencesXpoState")]
        public XPCollection<XpoTransition> XpoTransitions { get { return GetCollection<XpoTransition>(nameof(XpoTransitions)); } }
        [Association(@"XpoTransitionReferencesXpoState1")]
        public XPCollection<XpoTransition> XpoTransitions1 { get { return GetCollection<XpoTransition>(nameof(XpoTransitions1)); } }
    }

}
