//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoTrackingRecord : XPObject
    {
        Guid fInstanceId;
        public Guid InstanceId
        {
            get { return fInstanceId; }
            set { SetPropertyValue<Guid>(nameof(InstanceId), ref fInstanceId, value); }
        }
        DateTime fDateTime;
        public DateTime DateTime
        {
            get { return fDateTime; }
            set { SetPropertyValue<DateTime>(nameof(DateTime), ref fDateTime, value); }
        }
        string fData;
        [Size(SizeAttribute.Unlimited)]
        public string Data
        {
            get { return fData; }
            set { SetPropertyValue<string>(nameof(Data), ref fData, value); }
        }
        string fActivityId;
        public string ActivityId
        {
            get { return fActivityId; }
            set { SetPropertyValue<string>(nameof(ActivityId), ref fActivityId, value); }
        }
    }

}
