//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoUserActivityVersion : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fWorkflowUniqueId;
        public string WorkflowUniqueId
        {
            get { return fWorkflowUniqueId; }
            set { SetPropertyValue<string>(nameof(WorkflowUniqueId), ref fWorkflowUniqueId, value); }
        }
        string fXaml;
        [Size(SizeAttribute.Unlimited)]
        public string Xaml
        {
            get { return fXaml; }
            set { SetPropertyValue<string>(nameof(Xaml), ref fXaml, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>(nameof(Version), ref fVersion, value); }
        }
    }

}
