//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoWorkflowDefinition : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        [Size(255)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fXaml;
        [Size(SizeAttribute.Unlimited)]
        public string Xaml
        {
            get { return fXaml; }
            set { SetPropertyValue<string>(nameof(Xaml), ref fXaml, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>(nameof(TargetObjectType), ref fTargetObjectType, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>(nameof(Criteria), ref fCriteria, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        bool fAutoStartWhenObjectIsCreated;
        public bool AutoStartWhenObjectIsCreated
        {
            get { return fAutoStartWhenObjectIsCreated; }
            set { SetPropertyValue<bool>(nameof(AutoStartWhenObjectIsCreated), ref fAutoStartWhenObjectIsCreated, value); }
        }
        bool fAutoStartWhenObjectFitsCriteria;
        public bool AutoStartWhenObjectFitsCriteria
        {
            get { return fAutoStartWhenObjectFitsCriteria; }
            set { SetPropertyValue<bool>(nameof(AutoStartWhenObjectFitsCriteria), ref fAutoStartWhenObjectFitsCriteria, value); }
        }
        bool fAllowMultipleRuns;
        public bool AllowMultipleRuns
        {
            get { return fAllowMultipleRuns; }
            set { SetPropertyValue<bool>(nameof(AllowMultipleRuns), ref fAllowMultipleRuns, value); }
        }
    }

}
