//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoWorkflowInstanceControlCommandRequest : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fTargetWorkflowUniqueId;
        public string TargetWorkflowUniqueId
        {
            get { return fTargetWorkflowUniqueId; }
            set { SetPropertyValue<string>(nameof(TargetWorkflowUniqueId), ref fTargetWorkflowUniqueId, value); }
        }
        Guid fTargetActivityInstanceId;
        public Guid TargetActivityInstanceId
        {
            get { return fTargetActivityInstanceId; }
            set { SetPropertyValue<Guid>(nameof(TargetActivityInstanceId), ref fTargetActivityInstanceId, value); }
        }
        int fCommand;
        public int Command
        {
            get { return fCommand; }
            set { SetPropertyValue<int>(nameof(Command), ref fCommand, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fResult;
        [Size(SizeAttribute.Unlimited)]
        public string Result
        {
            get { return fResult; }
            set { SetPropertyValue<string>(nameof(Result), ref fResult, value); }
        }
    }

}
