//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Uwp_App5.RapidCM_PGS_Dev
{

    public partial class XpoWorkflowInstance : XPObject
    {
        string fOwner;
        public string Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<string>(nameof(Owner), ref fOwner, value); }
        }
        Guid fInstanceId;
        public Guid InstanceId
        {
            get { return fInstanceId; }
            set { SetPropertyValue<Guid>(nameof(InstanceId), ref fInstanceId, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        string fContent;
        [Size(SizeAttribute.Unlimited)]
        public string Content
        {
            get { return fContent; }
            set { SetPropertyValue<string>(nameof(Content), ref fContent, value); }
        }
        string fMetadata;
        [Size(SizeAttribute.Unlimited)]
        public string Metadata
        {
            get { return fMetadata; }
            set { SetPropertyValue<string>(nameof(Metadata), ref fMetadata, value); }
        }
        DateTime fExpirationDateTime;
        public DateTime ExpirationDateTime
        {
            get { return fExpirationDateTime; }
            set { SetPropertyValue<DateTime>(nameof(ExpirationDateTime), ref fExpirationDateTime, value); }
        }
    }

}
